// <auto-generated />
using System;
using BoscovsBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoscovsBackend.Migrations
{
    [DbContext(typeof(BoscovsDbContext))]
    partial class BoscovsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("BoscovsBackend.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("employee_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 2, 3, 17, 50, 34, 986, DateTimeKind.Local).AddTicks(251),
                            department = "IT",
                            employee_number = "1001",
                            first_name = "Mark",
                            job_title = "Developer",
                            last_name = "Fischer",
                            status = "Active"
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 2, 3, 17, 50, 34, 986, DateTimeKind.Local).AddTicks(255),
                            department = "Sales",
                            employee_number = "1002",
                            first_name = "John",
                            job_title = "Manager",
                            last_name = "Doe",
                            status = "Active"
                        });
                });

            modelBuilder.Entity("BoscovsBackend.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("access")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            access = "admin",
                            created_at = "2026-02-03 17:50:34",
                            email = "admin@boscovs.com",
                            password = "$2a$11$GFhmqt6w.rHc3Htj66tNa.elY54RTEgtq1SWsCjx24vsw8P395NHS",
                            status = "Active",
                            updated_at = "2026-02-03 17:50:34",
                            username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
